{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "a10-tkc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a10-tkc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "a10-tkc.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  # Allow all egress - TKC needs to access Kubernetes API and Thunder ADC
  - {}
{{- end }}
