{{- if .Values.networkPolicy.enabled }}
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "a10-tkc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a10-tkc.labels" . | nindent 4 }}
spec:
  podSelector:
    matchLabels:
      {{- include "a10-tkc.selectorLabels" . | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  # Allow Kubernetes API access
  - to:
    - namespaceSelector: {}
    ports:
    - protocol: TCP
      port: 443
    - protocol: TCP
      port: 6443
  # Allow DNS resolution (assumes kube-dns in kube-system)
  # For CoreDNS or custom DNS, update the label selector
  - to:
    - podSelector:
        matchLabels:
          k8s-app: kube-dns
    ports:
    - protocol: UDP
      port: 53
  {{- if .Values.thunder.host }}
  - to:
    - ipBlock:
        cidr: {{ .Values.thunder.host }}/32
    ports:
    - protocol: TCP
      port: {{ .Values.thunder.port }}
  {{- end }}
{{- end }}
