{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "a10-tkc.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a10-tkc.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "a10-tkc.selectorLabels" . | nindent 6 }}
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
{{- end }}
