{{/*
Cleanup RBAC resources for pre-delete hook
These resources allow the cleanup job to delete hook-created resources on uninstall
*/}}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "a10-slb.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a10-slb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "a10-slb.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a10-slb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
rules:
- apiGroups: ["tkc.a10networks.com"]
  resources: ["healthmonitors", "servicegroups", "virtualservers"]
  verbs: ["delete", "get", "list"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "a10-slb.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "a10-slb.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "a10-slb.fullname" . }}-cleanup
subjects:
- kind: ServiceAccount
  name: {{ include "a10-slb.fullname" . }}-cleanup
  namespace: {{ .Release.Namespace }}
